[package]
name = "tycho-emulator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
libc = { version = "0.2", optional = true }
log = "0.4"
num-bigint = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

everscale-types = { version = "0.1.2", default-features = false, features = [
    "sync",
    "serde",
    "base64",
] }
everscale-vm = { git = "https://github.com/broxus/everscale-vm.git", rev = "100d1a5e5c87" }

[build-dependencies]
anyhow = "1.0"

[features]
native = ["libc"]

[patch.crates-io]
everscale-types = { git = "https://github.com/broxus/everscale-types.git", rev = "6e3c289f9bbf46337b11b24656a9c87ce409323e" }
